[package]
name = "intelligence-emulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "intelligence-emulator"
path = "src/main.rs"

[dependencies]
blake3.workspace = true
clap.workspace = true
intelligence-intelligence = { path = "../intelligence" }
intelligence-protocol = { path = "../protocol" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
